# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0014_auto_20151203_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 17, 41, 16, 592820, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 17, 41, 16, 592875, tzinfo=utc)),
        ),
    ]
