# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0015_auto_20151204_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 18, 39, 37, 741226, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 18, 39, 37, 741277, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='flower',
            name='size',
            field=models.ManyToManyField(to='flowers.Size'),
        ),
    ]
