# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0016_auto_20151204_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 19, 36, 29, 660367, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 19, 36, 29, 660409, tzinfo=utc)),
        ),
    ]
