# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0017_auto_20151204_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 19, 42, 33, 286677, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 4, 19, 42, 33, 286725, tzinfo=utc)),
        ),
    ]
