# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20151215_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 26, 12, 6, 2, 29517, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 26, 12, 6, 2, 29447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 26, 12, 6, 2, 29548, tzinfo=utc)),
        ),
    ]
