# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0012_auto_20151203_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 3, 19, 47, 34, 381059, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 3, 19, 47, 34, 381102, tzinfo=utc)),
        ),
    ]
