# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0023_auto_20151211_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 12, 10, 4, 16, 289957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 12, 10, 4, 16, 290000, tzinfo=utc)),
        ),
    ]
