# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0024_auto_20151212_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers.Type'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 12, 10, 5, 47, 564663, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 12, 10, 5, 47, 564724, tzinfo=utc)),
        ),
    ]
