# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0027_auto_20151212_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 26, 12, 6, 2, 18595, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 26, 12, 6, 2, 18640, tzinfo=utc)),
        ),
    ]
