# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flowers', '0018_auto_20151204_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.Flower')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.Size')),
            ],
            options={
                'ordering': ['added_at'],
                'db_table': 'cart_items',
            },
        ),
    ]
